dismissalertpath ='/html/body/div/div[3]/div/div[2]/div[3]/div/span/span'
emailpath = '//*[@id="identifierId"]'
joinmeetxpath ='/html/body/div[2]/div[2]/div[5]/div[2]/aside/div/div[1]/div/div[2]/div/a'
classroompath ='/html/body/div[2]/div[1]/div[6]/div/ol/li[4]/div[1]/div[3]/h2/a[1]'
buttonxpath = '/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div/div[2]/div/div[2]/div/div[1]/div/div/button/span'
passwordXpath = '/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div/div[2]/div/div[1]/div/form/span/section/div/div/div[1]/div[1]/div/div/div/div/div[1]/div/div[1]/input'
passwordbuttonxpath = '/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div/div[2]/div/div[2]/div/div[1]/div/div/button'
meetbutton ='/html/body/div[1]/c-wiz/div/div/div[9]/div[3]/div/div/div[3]/div/div/div[2]/div/div[2]/div/div[1]/div[1]/span'
join_meeting_path= '/html/body/div[1]/c-wiz/div/div/div[9]/div[3]/div/div/div[3]/div/div/div[2]/div/div[2]/div/div[1]/div[1]/span/span'